### ISSUE TITLE
Error installing dependencies: "TypeError: __init__() got an unexpected keyword argument 'capture_output'"

### ISSUE THREAD

**Issue by awoSYS** [irisTa56/markdown2textile#6]
Hi!
I just installed your VS extension from within VS Code. When I reopen VSC after installing the extension and clicking "install missing dependencies" (or something like that), I get an error message:
```
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```
Any ideas about that?
I use VSC 1.39.2 on Ubuntu 18.04. 
Thanks in advance! ;)

**Comment by irisTa56** [comment]
Sorry for the late reply.
It seems [a problem associated with Python < 3.7](https://stackoverflow.com/questions/53209127/subprocess-unexpected-keyword-argument-capture-output/53209196).
I'll fix it.
